buildscript {
    ext {
        buildToolsVersion = "34.0.0"
        minSdkVersion = 24
        compileSdkVersion = 34
        targetSdkVersion = 34
        kotlinVersion = "1.9.24"
    }
    buildscript {
    repositories {
        google()
        maven { url "https://maven.google.com" }
        // Rimuoviamo mavenCentral() temporaneamente per forzare Google
    }
    dependencies {
        classpath("com.android.tools.build:gradle:8.2.2")
        classpath("org.jetbrains.kotlin:kotlin-gradle-plugin:1.9.24")
    }
}
