# JVM memory (fondamentale su GitHub Actions)
org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -Dkotlin.daemon.jvm.options=-Xmx2048m

# Performance
org.gradle.parallel=true
org.gradle.daemon=true
org.gradle.configureondemand=true

# AndroidX
android.useAndroidX=true
android.enableJetifier=true
