pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        // L'ordine qui è fondamentale per evitare il 403
        google()
        maven { url "https://maven.google.com" }
        maven { url "https://plugins.gradle.org/m2/" }
        mavenCentral() 
    }
}

rootProject.name = "UnionHubApp"
include(":app")
