pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        maven { url "https://maven.google.com" }
        // Se proprio serve Maven, usiamo la versione HTTPS forzata
        maven { 
            url "https://repo.maven.apache.org/maven2/"
            allowInsecureProtocol = false
    }
}

rootProject.name = "UnionHubApp"
include(":app")
