pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        google()
        // Mirror di Cloudflare: molto più affidabile per GitHub Actions
        maven { url "https://cloudflare.com/maven" } 
        // JitPack come backup per librerie ostiche
        maven { url "https://jitpack.io" }
        mavenCentral()
    }
}

rootProject.name = "UnionHubApp"
include(":app")
