android {
    namespace "com.unionhub.app"

    defaultConfig {
        applicationId "com.unionhub.app"
        minSdkVersion rootProject.ext.minSdkVersion
        targetSdkVersion rootProject.ext.targetSdkVersion
        versionCode 1
        versionName "1.0"
    }

    buildFeatures {
        buildConfig true
    }
}
